### ISSUE TITLE
generate gradle jenkins slave

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-slave#9]
need jenkins-slave with ability to build any gradle programs

**Comment by mgolokhov** [comment]
**Investigation:**

- _Do we have any official images in Docker Hub?_
Yes we [do](https://hub.docker.com/_/gradle/?tab=description).

- _What is the gradle:latest image?_
[Dockerfile](https://github.com/keeganwitt/docker-gradle/blob/a30081138c400ea1fc9b99c5fb6088ae39571552/jdk8/Dockerfile)
It's based on gradle 6.2.2, adoptopenjdk:8-jdk-hotspot (1.8.0_242-b08)
Size: 278.02 MB (packed) and 557MB (unpacked)
`uname -r`: [4.19.76-linuxkit](https://github.com/linuxkit/linuxkit)

- _Are there any smaller images?_
Yes, they are based on [alpine](https://hub.docker.com/_/gradle?tab=tags&page=1&name=alpine)
Size: ~154 MB (packed)

- _Why I do not see Dockerfiles for alpine in [master branch](https://github.com/keeganwitt/docker-gradle/tree/master)?_ 
Alpine was dropped because AdoptOpenJDK alpine is [unofficial](https://hub.docker.com/r/adoptopenjdk/openjdk11)

- _What issues we may have with unofficial images?_
TODO

- _Can we can reuse at least official images?_
I do not see any barriers.

**Comment by vdelendik** [comment]
gradle already intergated into the default jenkins-slave image
